# Generated by Django 3.2.6 on 2021-08-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
