# Generated by Django 3.2.6 on 2021-08-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_remove_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
